name: Deploy Aliyun oss

# Controls when the workflow will run
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Jekyll Pages
        run: |
          jekyll build --trace --baseurl /plugins

  deploy-aliyun-oss-canary:
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/master' }}
    needs: build
      - name: Upload Canary
        uses: Menci/upload-to-oss@beta-v3
        with:
          access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          bucket: inpageedit-dev
          endpoint: https://canary.ipe.wiki
          local-path: _site
          remote-path: plugins/${{ github.ref_name }}
          delay-html-file-upload: true
          no-delete-remote-files: false

  deploy-aliyun-oss-prod:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: build
      - name: Upload Production
        uses: Menci/upload-to-oss@beta-v3
        with:
          access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          bucket: inpageedit-prod
          endpoint: https://app.ipe.wiki
          local-path: _site
          remote-path: plugins
          delay-html-file-upload: true
          no-delete-remote-files: false
